apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls-{{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.crt | default "nocert" | b64enc }}
  tls.key: |
    {{ .Values.key | default "nocert" | b64enc }}