apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    component: client-{{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.microservices.targetPort }}