{{ if .Values.deployWithAGIC }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-admin-{{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
spec:
  rules:
  - http:
        paths:
          - path: /admin/*
            pathType: Prefix
            backend:
              service:
                name: admin-cluster-ip-{{ .Release.Name }}
                port:
                  number: 80

{{ end }}