apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-ip-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    component: mysql-{{ .Release.Name }}
  ports:
    - port: 3306
      targetPort: 3306