apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql-{{ .Release.Name }}
  template:
    metadata:
      labels:
        component: mysql-{{ .Release.Name }}
    spec:
      volumes:
        - name: mysql-storage-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: mysql-persistent-volume-claim-{{ .Release.Name }}
      containers:
        - name: mysql-{{ .Release.Name }}
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worldapp-secrets-{{ .Release.Name }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: worldapp-secrets-{{ .Release.Name }}
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worldapp-secrets-{{ .Release.Name }}
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: world
          volumeMounts:
            - name: mysql-storage-{{ .Release.Name }}
              mountPath: /var/lib/mysql



