apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    component: redis-{{ .Release.Name }}
  ports:
    - port: 6379
      targetPort: 6379