apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis-{{ .Release.Name }}
  template:
    metadata:
      labels:
        component: redis-{{ .Release.Name }}
    spec:
      containers:
        - name: redis-{{ .Release.Name }}
          image: redis
          ports:
            - containerPort: 6379
