apiVersion: v1
kind: Secret
metadata:
  name: worldapp-secrets-{{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysql_root_password }}
  MYSQL_USER: {{ .Values.secret.mysql_user }}
  MYSQL_PASSWORD: {{ .Values.secret.mysql_password }}
  ADMIN_USER: {{ .Values.secret.admin_user }}
  ADMIN_PASSWORD: {{ .Values.secret.admin_password }}
  SECRET_KEY: {{ randAlphaNum 32 | nospace }}