- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages base packages
  apt:
    name:
    - apache2
    - libapache2-mod-wsgi-py3
    - python3-pip
    state: present
    install_recommends: no

- name: Enable mod Headers
  apache2_module:
      state: present
      name: headers
  notify: restart apache

- name: Disable default Virtual Host
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache

- name: Start service Apache2, if not started
  service:
    name: apache2
    state: started
    enabled: yes